# Site settings
title: Meadow House Floral Design
email: meadowhousefloral@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Custom wedding floral design for the New York couple.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
instagram_username: meadowhousefloral

# Build settings
markdown: kramdown
